
/*
edgeList: 边数据集合
edge: 
	"id": id
	"uniqueId": 唯一id，同一个uniqueId可以会存在2个id的边，一个是运行状态，一个是非运行状态
	"elementType": 固定值"E"
	"status": 状态值，不同状态值显示不同颜色
	"type": 边的名称
	"source": 起点的id,
	"target": 终点的id,
	"graphId": 所属图的id

node:
	"id": id
	"uniqueId": 唯一id，同一个uniqueId可以会存在2个id的边，一个是运行状态，一个是非运行状态
	"elementType": 固定值"N"
	"status": 状态值，不同状态值显示不同颜色
	"type": 点的名称
	"graphId": 所属图的id
其他没有提到的字段可以暂时不用关注。
状态枚举：
	10: 草稿
	8: 已提交
	70: 已验证
	40: 待发布
	60: 正式运行
	只有待发布和正式运行的节点间才可以创建边。
*/

const data = {
  "edgeList": [{
    "rate": 0,
    "elementType": "E",
    "directed": "Y",
    "update": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"src\",\"propName\":\"src_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dst\",\"propName\":\"dst_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"srcType\",\"propName\":\"src_type\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dstType\",\"propName\":\"dst_type\",\"propOnLine\":1}]",
    "ttl": "30d",
    "graphId": 5,
    "online": 1,
    "source": 12,
    "type": "medium_merchant_id2user_id_offline",
    "target": 13,
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "商户2PARTENER",
    "gmtCreate": "2018-04-03 14:42:00",
    "id": 84,
    "status": 60,
    "uniqueId": 84
  }, {
    "rate": 0,
    "elementType": "E",
    "directed": "Y",
    "update": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"src\",\"propName\":\"src_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dst\",\"propName\":\"dst_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"srcType\",\"propName\":\"src_type\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dstType\",\"propName\":\"dst_type\",\"propOnLine\":1}]",
    "ttl": "30d",
    "graphId": 5,
    "online": 1,
    "source": 13,
    "type": "medium_user_id2phone_no_offline",
    "target": 18,
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "user2phone",
    "gmtCreate": "2018-04-03 14:45:59",
    "id": 85,
    "status": 60,
    "uniqueId": 85
  }, {
    "rate": 0,
    "elementType": "E",
    "directed": "Y",
    "update": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"src\",\"propName\":\"src_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dst\",\"propName\":\"dst_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"srcType\",\"propName\":\"src_type\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dstType\",\"propName\":\"dst_type\",\"propOnLine\":1}]",
    "ttl": "30d",
    "graphId": 5,
    "online": 1,
    "source": 13,
    "type": "medium_user_id2cert_no_offline",
    "target": 14,
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "user2cert",
    "gmtCreate": "2018-04-03 15:39:36",
    "id": 86,
    "status": 60,
    "uniqueId": 86
  }, {
    "rate": 0,
    "elementType": "E",
    "directed": "Y",
    "update": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"src\",\"propName\":\"src_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dst\",\"propName\":\"dst_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"srcType\",\"propName\":\"src_type\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dstType\",\"propName\":\"dst_type\",\"propOnLine\":1}]",
    "ttl": "30d",
    "graphId": 5,
    "online": 1,
    "source": 12,
    "type": "medium_merchant_id2license_number_offline",
    "target": 15,
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "merchant2license",
    "gmtCreate": "2018-04-03 16:16:01",
    "id": 87,
    "status": 60,
    "uniqueId": 87
  }, {
    "rate": 0,
    "elementType": "E",
    "directed": "Y",
    "update": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"src\",\"propName\":\"src_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dst\",\"propName\":\"dst_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"srcType\",\"propName\":\"src_type\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dstType\",\"propName\":\"dst_type\",\"propOnLine\":1}]",
    "ttl": "30d",
    "graphId": 5,
    "online": 1,
    "source": 13,
    "type": "medium_user_id2wx_qq_offline",
    "target": 20,
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "user2wxqq",
    "gmtCreate": "2018-04-03 16:47:32",
    "id": 88,
    "status": 60,
    "uniqueId": 88
  }, {
    "rate": 0,
    "elementType": "E",
    "directed": "Y",
    "update": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"src\",\"propName\":\"src_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dst\",\"propName\":\"dst_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"srcType\",\"propName\":\"src_type\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dstType\",\"propName\":\"dst_type\",\"propOnLine\":1}]",
    "ttl": "30d",
    "graphId": 5,
    "online": 1,
    "source": 13,
    "type": "medium_user_id2web_url_offline",
    "target": 21,
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "user2url",
    "gmtCreate": "2018-04-04 10:06:02",
    "id": 89,
    "status": 60,
    "uniqueId": 89
  }, {
    "rate": 0,
    "elementType": "E",
    "directed": "Y",
    "update": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"src\",\"propName\":\"src_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dst\",\"propName\":\"dst_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"srcType\",\"propName\":\"src_type\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dstType\",\"propName\":\"dst_type\",\"propOnLine\":1}]",
    "ttl": "30d",
    "graphId": 5,
    "online": 1,
    "source": 13,
    "type": "medium_user_id2isv_pid_offline",
    "target": 19,
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "user2isv_pid",
    "gmtCreate": "2018-04-04 10:07:08",
    "id": 90,
    "status": 60,
    "uniqueId": 90
  }, {
    "rate": 0,
    "elementType": "E",
    "directed": "Y",
    "update": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"src\",\"propName\":\"src_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dst\",\"propName\":\"dst_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"srcType\",\"propName\":\"src_type\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dstType\",\"propName\":\"dst_type\",\"propOnLine\":1}]",
    "ttl": "30d",
    "graphId": 5,
    "online": 1,
    "source": 13,
    "type": "medium_user_id2bank_card_no_offline",
    "target": 16,
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "user2bank_card",
    "gmtCreate": "2018-04-04 10:09:05",
    "id": 91,
    "status": 60,
    "uniqueId": 91
  }, {
    "rate": 0,
    "elementType": "E",
    "directed": "Y",
    "update": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"src\",\"propName\":\"src_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dst\",\"propName\":\"dst_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"srcType\",\"propName\":\"src_type\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dstType\",\"propName\":\"dst_type\",\"propOnLine\":1}]",
    "ttl": "30d",
    "graphId": 5,
    "online": 1,
    "source": 13,
    "type": "medium_user_id2receiver_card_no_offline",
    "target": 29,
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "user2receiver",
    "gmtCreate": "2018-04-04 10:34:52",
    "id": 92,
    "status": 60,
    "uniqueId": 92
  }, {
    "rate": -4,
    "elementType": "E",
    "directed": "Y",
    "update": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"src\",\"propName\":\"src_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dst\",\"propName\":\"dst_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"srcType\",\"propName\":\"src_type\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dstType\",\"propName\":\"dst_type\",\"propOnLine\":1}]",
    "ttl": "30d",
    "graphId": 5,
    "online": 1,
    "source": 13,
    "type": "medium_user_id2umid_login",
    "target": 22,
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "user2umin_login",
    "gmtCreate": "2018-04-04 11:22:46",
    "id": 93,
    "status": 60,
    "uniqueId": 93
  }, {
    "rate": -3,
    "elementType": "E",
    "directed": "Y",
    "update": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"src\",\"propName\":\"src_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dst\",\"propName\":\"dst_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"srcType\",\"propName\":\"src_type\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dstType\",\"propName\":\"dst_type\",\"propOnLine\":1}]",
    "ttl": "30d",
    "graphId": 5,
    "online": 1,
    "source": 13,
    "type": "medium_user_id2umid_maintrade",
    "target": 22,
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "user2umid_maintrade",
    "gmtCreate": "2018-04-04 11:24:20",
    "id": 94,
    "status": 60,
    "uniqueId": 94
  }, {
    "rate": -2,
    "elementType": "E",
    "directed": "Y",
    "update": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"src\",\"propName\":\"src_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dst\",\"propName\":\"dst_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"srcType\",\"propName\":\"src_type\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dstType\",\"propName\":\"dst_type\",\"propOnLine\":1}]",
    "ttl": "30d",
    "graphId": 5,
    "online": 1,
    "source": 13,
    "type": "medium_user_id2umid_highrisk",
    "target": 22,
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "medium_user_id2umid_highrisk",
    "gmtCreate": "2018-04-04 11:25:27",
    "id": 95,
    "status": 60,
    "uniqueId": 95
  }, {
    "rate": -1,
    "elementType": "E",
    "directed": "Y",
    "update": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"src\",\"propName\":\"src_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dst\",\"propName\":\"dst_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"srcType\",\"propName\":\"src_type\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dstType\",\"propName\":\"dst_type\",\"propOnLine\":1}]",
    "ttl": "30d",
    "graphId": 5,
    "online": 1,
    "source": 13,
    "type": "medium_user_id2umid_trade",
    "target": 22,
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "medium_user_id2umid_trade",
    "gmtCreate": "2018-04-04 11:26:30",
    "id": 96,
    "status": 60,
    "uniqueId": 96
  }, {
    "rate": 0,
    "elementType": "E",
    "directed": "Y",
    "update": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"src\",\"propName\":\"src_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dst\",\"propName\":\"dst_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"srcType\",\"propName\":\"src_type\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dstType\",\"propName\":\"dst_type\",\"propOnLine\":1}]",
    "ttl": "30d",
    "graphId": 5,
    "online": 1,
    "source": 13,
    "type": "medium_user_id2umid_tenant",
    "target": 22,
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "medium_user_id2umid_tenant",
    "gmtCreate": "2018-04-04 11:28:59",
    "id": 97,
    "status": 60,
    "uniqueId": 97
  }, {
    "rate": 1,
    "elementType": "E",
    "directed": "Y",
    "update": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"src\",\"propName\":\"src_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dst\",\"propName\":\"dst_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"srcType\",\"propName\":\"src_type\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dstType\",\"propName\":\"dst_type\",\"propOnLine\":1}]",
    "ttl": "30d",
    "graphId": 5,
    "online": 1,
    "source": 13,
    "type": "medium_user_id2umid_otherpay",
    "target": 22,
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "medium_user_id2umid_otherpay",
    "gmtCreate": "2018-04-04 11:30:02",
    "id": 98,
    "status": 60,
    "uniqueId": 98
  }, {
    "rate": 2,
    "elementType": "E",
    "directed": "Y",
    "update": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"src\",\"propName\":\"src_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dst\",\"propName\":\"dst_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"srcType\",\"propName\":\"src_type\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dstType\",\"propName\":\"dst_type\",\"propOnLine\":1}]",
    "ttl": "30d",
    "graphId": 5,
    "online": 1,
    "source": 13,
    "type": "medium_user_id2umid_auth",
    "target": 22,
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "medium_user_id2umid_auth",
    "gmtCreate": "2018-04-04 11:31:03",
    "id": 99,
    "status": 60,
    "uniqueId": 99
  }, {
    "rate": 3,
    "elementType": "E",
    "directed": "Y",
    "update": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"src\",\"propName\":\"src_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dst\",\"propName\":\"dst_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"srcType\",\"propName\":\"src_type\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dstType\",\"propName\":\"dst_type\",\"propOnLine\":1}]",
    "ttl": "30d",
    "graphId": 5,
    "online": 1,
    "source": 13,
    "type": "medium_user_id2umid_register",
    "target": 22,
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "medium_user_id2umid_register",
    "gmtCreate": "2018-04-04 11:31:49",
    "id": 100,
    "status": 60,
    "uniqueId": 100
  }, {
    "rate": -4,
    "elementType": "E",
    "directed": "Y",
    "update": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"src\",\"propName\":\"src_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dst\",\"propName\":\"dst_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"srcType\",\"propName\":\"src_type\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dstType\",\"propName\":\"dst_type\",\"propOnLine\":1}]",
    "ttl": "30d",
    "graphId": 5,
    "online": 1,
    "source": 13,
    "type": "medium_user_id2tid_login",
    "target": 23,
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "medium_user_id2tid_login",
    "gmtCreate": "2018-04-04 11:33:01",
    "id": 101,
    "status": 60,
    "uniqueId": 101
  }, {
    "rate": -3,
    "elementType": "E",
    "directed": "Y",
    "update": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"src\",\"propName\":\"src_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dst\",\"propName\":\"dst_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"srcType\",\"propName\":\"src_type\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dstType\",\"propName\":\"dst_type\",\"propOnLine\":1}]",
    "ttl": "30d",
    "graphId": 5,
    "online": 1,
    "source": 13,
    "type": "medium_user_id2tid_maintrade",
    "target": 23,
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "medium_user_id2tid_maintrade",
    "gmtCreate": "2018-04-04 11:33:51",
    "id": 102,
    "status": 60,
    "uniqueId": 102
  }, {
    "rate": -2,
    "elementType": "E",
    "directed": "Y",
    "update": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"src\",\"propName\":\"src_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dst\",\"propName\":\"dst_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"srcType\",\"propName\":\"src_type\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dstType\",\"propName\":\"dst_type\",\"propOnLine\":1}]",
    "ttl": "30d",
    "graphId": 5,
    "online": 1,
    "source": 13,
    "type": "medium_user_id2tid_highrisk",
    "target": 23,
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "medium_user_id2tid_highrisk",
    "gmtCreate": "2018-04-04 11:34:36",
    "id": 103,
    "status": 60,
    "uniqueId": 103
  }, {
    "rate": -1,
    "elementType": "E",
    "directed": "Y",
    "update": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"src\",\"propName\":\"src_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dst\",\"propName\":\"dst_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"srcType\",\"propName\":\"src_type\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dstType\",\"propName\":\"dst_type\",\"propOnLine\":1}]",
    "ttl": "30d",
    "graphId": 5,
    "online": 1,
    "source": 13,
    "type": "medium_user_id2tid_trade",
    "target": 23,
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "medium_user_id2tid_trade",
    "gmtCreate": "2018-04-04 11:35:26",
    "id": 104,
    "status": 60,
    "uniqueId": 104
  }, {
    "rate": 0,
    "elementType": "E",
    "directed": "Y",
    "update": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"src\",\"propName\":\"src_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dst\",\"propName\":\"dst_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"srcType\",\"propName\":\"src_type\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dstType\",\"propName\":\"dst_type\",\"propOnLine\":1}]",
    "ttl": "30d",
    "graphId": 5,
    "online": 1,
    "source": 13,
    "type": "medium_user_id2tid_tenant",
    "target": 23,
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "medium_user_id2tid_tenant",
    "gmtCreate": "2018-04-04 11:36:32",
    "id": 105,
    "status": 60,
    "uniqueId": 105
  }, {
    "rate": 1,
    "elementType": "E",
    "directed": "Y",
    "update": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"src\",\"propName\":\"src_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dst\",\"propName\":\"dst_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"srcType\",\"propName\":\"src_type\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dstType\",\"propName\":\"dst_type\",\"propOnLine\":1}]",
    "ttl": "30d",
    "graphId": 5,
    "online": 1,
    "source": 13,
    "type": "medium_user_id2tid_otherpay",
    "target": 23,
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "medium_user_id2tid_otherpay",
    "gmtCreate": "2018-04-04 11:37:22",
    "id": 106,
    "status": 60,
    "uniqueId": 106
  }, {
    "rate": 2,
    "elementType": "E",
    "directed": "Y",
    "update": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"src\",\"propName\":\"src_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dst\",\"propName\":\"dst_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"srcType\",\"propName\":\"src_type\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dstType\",\"propName\":\"dst_type\",\"propOnLine\":1}]",
    "ttl": "30d",
    "graphId": 5,
    "online": 1,
    "source": 13,
    "type": "medium_user_id2tid_auth",
    "target": 23,
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "medium_user_id2tid_auth",
    "gmtCreate": "2018-04-04 11:38:07",
    "id": 107,
    "status": 60,
    "uniqueId": 107
  }, {
    "rate": 3,
    "elementType": "E",
    "directed": "Y",
    "update": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"src\",\"propName\":\"src_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dst\",\"propName\":\"dst_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"srcType\",\"propName\":\"src_type\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dstType\",\"propName\":\"dst_type\",\"propOnLine\":1}]",
    "ttl": "30d",
    "graphId": 5,
    "online": 1,
    "source": 13,
    "type": "medium_user_id2tid_register",
    "target": 23,
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "medium_user_id2tid_register",
    "gmtCreate": "2018-04-04 11:38:55",
    "id": 108,
    "status": 60,
    "uniqueId": 108
  }, {
    "rate": -4,
    "elementType": "E",
    "directed": "Y",
    "update": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"src\",\"propName\":\"src_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dst\",\"propName\":\"dst_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"srcType\",\"propName\":\"src_type\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dstType\",\"propName\":\"dst_type\",\"propOnLine\":1}]",
    "ttl": "30d",
    "graphId": 5,
    "online": 1,
    "source": 13,
    "type": "medium_user_id2imei_login",
    "target": 24,
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "medium_user_id2imei_login",
    "gmtCreate": "2018-04-04 11:39:38",
    "id": 109,
    "status": 60,
    "uniqueId": 109
  }, {
    "rate": -3,
    "elementType": "E",
    "directed": "Y",
    "update": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"src\",\"propName\":\"src_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dst\",\"propName\":\"dst_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"srcType\",\"propName\":\"src_type\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dstType\",\"propName\":\"dst_type\",\"propOnLine\":1}]",
    "ttl": "30d",
    "graphId": 5,
    "online": 1,
    "source": 13,
    "type": "medium_user_id2imei_maintrade",
    "target": 24,
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "medium_user_id2imei_maintrade",
    "gmtCreate": "2018-04-04 11:40:45",
    "id": 110,
    "status": 60,
    "uniqueId": 110
  }, {
    "rate": -2,
    "elementType": "E",
    "directed": "Y",
    "update": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"src\",\"propName\":\"src_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dst\",\"propName\":\"dst_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"srcType\",\"propName\":\"src_type\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dstType\",\"propName\":\"dst_type\",\"propOnLine\":1}]",
    "ttl": "30d",
    "graphId": 5,
    "online": 1,
    "source": 13,
    "type": "medium_user_id2imei_highrisk",
    "target": 24,
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "medium_user_id2imei_highrisk",
    "gmtCreate": "2018-04-04 11:41:27",
    "id": 111,
    "status": 60,
    "uniqueId": 111
  }, {
    "rate": -1,
    "elementType": "E",
    "directed": "Y",
    "update": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"src\",\"propName\":\"src_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dst\",\"propName\":\"dst_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"srcType\",\"propName\":\"src_type\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dstType\",\"propName\":\"dst_type\",\"propOnLine\":1}]",
    "ttl": "30d",
    "graphId": 5,
    "online": 1,
    "source": 13,
    "type": "medium_user_id2imei_trade",
    "target": 24,
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "medium_user_id2imei_trade",
    "gmtCreate": "2018-04-04 11:42:18",
    "id": 112,
    "status": 60,
    "uniqueId": 112
  }, {
    "rate": 0,
    "elementType": "E",
    "directed": "Y",
    "update": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"src\",\"propName\":\"src_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dst\",\"propName\":\"dst_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"srcType\",\"propName\":\"src_type\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dstType\",\"propName\":\"dst_type\",\"propOnLine\":1}]",
    "ttl": "30d",
    "graphId": 5,
    "online": 1,
    "source": 13,
    "type": "medium_user_id2imei_tenant",
    "target": 24,
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "medium_user_id2imei_tenant",
    "gmtCreate": "2018-04-04 11:42:58",
    "id": 113,
    "status": 60,
    "uniqueId": 113
  }, {
    "rate": 1,
    "elementType": "E",
    "directed": "Y",
    "update": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"src\",\"propName\":\"src_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dst\",\"propName\":\"dst_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"srcType\",\"propName\":\"src_type\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dstType\",\"propName\":\"dst_type\",\"propOnLine\":1}]",
    "ttl": "30d",
    "graphId": 5,
    "online": 1,
    "source": 13,
    "type": "medium_user_id2imei_otherpay",
    "target": 24,
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "medium_user_id2imei_otherpay",
    "gmtCreate": "2018-04-04 11:45:07",
    "id": 114,
    "status": 60,
    "uniqueId": 114
  }, {
    "rate": 2,
    "elementType": "E",
    "directed": "Y",
    "update": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"src\",\"propName\":\"src_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dst\",\"propName\":\"dst_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"srcType\",\"propName\":\"src_type\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dstType\",\"propName\":\"dst_type\",\"propOnLine\":1}]",
    "ttl": "30d",
    "graphId": 5,
    "online": 1,
    "source": 13,
    "type": "medium_user_id2imei_auth",
    "target": 24,
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "medium_user_id2imei_auth",
    "gmtCreate": "2018-04-04 11:45:50",
    "id": 115,
    "status": 60,
    "uniqueId": 115
  }, {
    "rate": 3,
    "elementType": "E",
    "directed": "Y",
    "update": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"src\",\"propName\":\"src_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dst\",\"propName\":\"dst_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"srcType\",\"propName\":\"src_type\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dstType\",\"propName\":\"dst_type\",\"propOnLine\":1}]",
    "ttl": "30d",
    "graphId": 5,
    "online": 1,
    "source": 13,
    "type": "medium_user_id2imei_register",
    "target": 24,
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "medium_user_id2imei_register",
    "gmtCreate": "2018-04-04 11:46:41",
    "id": 116,
    "status": 60,
    "uniqueId": 116
  }, {
    "rate": -4,
    "elementType": "E",
    "directed": "Y",
    "update": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"src\",\"propName\":\"src_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dst\",\"propName\":\"dst_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"srcType\",\"propName\":\"src_type\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dstType\",\"propName\":\"dst_type\",\"propOnLine\":1}]",
    "ttl": "30d",
    "graphId": 5,
    "online": 1,
    "source": 13,
    "type": "medium_user_id2sim_login",
    "target": 25,
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "medium_user_id2sim_login",
    "gmtCreate": "2018-04-04 11:47:20",
    "id": 117,
    "status": 60,
    "uniqueId": 117
  }, {
    "rate": -3,
    "elementType": "E",
    "directed": "Y",
    "update": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"src\",\"propName\":\"src_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dst\",\"propName\":\"dst_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"srcType\",\"propName\":\"src_type\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dstType\",\"propName\":\"dst_type\",\"propOnLine\":1}]",
    "ttl": "30d",
    "graphId": 5,
    "online": 1,
    "source": 13,
    "type": "medium_user_id2sim_maintrade",
    "target": 25,
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "medium_user_id2sim_maintrade",
    "gmtCreate": "2018-04-04 11:48:08",
    "id": 118,
    "status": 60,
    "uniqueId": 118
  }, {
    "rate": -2,
    "elementType": "E",
    "directed": "Y",
    "update": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"src\",\"propName\":\"src_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dst\",\"propName\":\"dst_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"srcType\",\"propName\":\"src_type\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dstType\",\"propName\":\"dst_type\",\"propOnLine\":1}]",
    "ttl": "30d",
    "graphId": 5,
    "online": 1,
    "source": 13,
    "type": "medium_user_id2sim_highrisk",
    "target": 25,
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "medium_user_id2sim_highrisk",
    "gmtCreate": "2018-04-04 11:49:06",
    "id": 119,
    "status": 60,
    "uniqueId": 119
  }, {
    "rate": -1,
    "elementType": "E",
    "directed": "Y",
    "update": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"src\",\"propName\":\"src_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dst\",\"propName\":\"dst_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"srcType\",\"propName\":\"src_type\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dstType\",\"propName\":\"dst_type\",\"propOnLine\":1}]",
    "ttl": "30d",
    "graphId": 5,
    "online": 1,
    "source": 13,
    "type": "medium_user_id2sim_trade",
    "target": 25,
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "medium_user_id2sim_trade",
    "gmtCreate": "2018-04-04 11:49:55",
    "id": 120,
    "status": 60,
    "uniqueId": 120
  }, {
    "rate": 0,
    "elementType": "E",
    "directed": "Y",
    "update": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"src\",\"propName\":\"src_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dst\",\"propName\":\"dst_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"srcType\",\"propName\":\"src_type\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dstType\",\"propName\":\"dst_type\",\"propOnLine\":1}]",
    "ttl": "30d",
    "graphId": 5,
    "online": 1,
    "source": 13,
    "type": "medium_user_id2sim_tenant",
    "target": 25,
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "medium_user_id2sim_tenant",
    "gmtCreate": "2018-04-04 11:50:34",
    "id": 121,
    "status": 60,
    "uniqueId": 121
  }, {
    "rate": 1,
    "elementType": "E",
    "directed": "Y",
    "update": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"src\",\"propName\":\"src_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dst\",\"propName\":\"dst_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"srcType\",\"propName\":\"src_type\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dstType\",\"propName\":\"dst_type\",\"propOnLine\":1}]",
    "ttl": "30d",
    "graphId": 5,
    "online": 1,
    "source": 13,
    "type": "medium_user_id2sim_otherpay",
    "target": 25,
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "medium_user_id2sim_otherpay",
    "gmtCreate": "2018-04-04 11:51:16",
    "id": 122,
    "status": 60,
    "uniqueId": 122
  }, {
    "rate": 2,
    "elementType": "E",
    "directed": "Y",
    "update": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"src\",\"propName\":\"src_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dst\",\"propName\":\"dst_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"srcType\",\"propName\":\"src_type\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dstType\",\"propName\":\"dst_type\",\"propOnLine\":1}]",
    "ttl": "30d",
    "graphId": 5,
    "online": 1,
    "source": 13,
    "type": "medium_user_id2sim_auth",
    "target": 25,
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "medium_user_id2sim_auth",
    "gmtCreate": "2018-04-04 11:51:58",
    "id": 123,
    "status": 60,
    "uniqueId": 123
  }, {
    "rate": 3,
    "elementType": "E",
    "directed": "Y",
    "update": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"src\",\"propName\":\"src_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dst\",\"propName\":\"dst_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"srcType\",\"propName\":\"src_type\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dstType\",\"propName\":\"dst_type\",\"propOnLine\":1}]",
    "ttl": "30d",
    "graphId": 5,
    "online": 1,
    "source": 13,
    "type": "medium_user_id2sim_register",
    "target": 25,
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "medium_user_id2sim_register",
    "gmtCreate": "2018-04-04 11:52:40",
    "id": 124,
    "status": 60,
    "uniqueId": 124
  }, {
    "rate": -4,
    "elementType": "E",
    "directed": "Y",
    "update": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"src\",\"propName\":\"src_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dst\",\"propName\":\"dst_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"srcType\",\"propName\":\"src_type\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dstType\",\"propName\":\"dst_type\",\"propOnLine\":1}]",
    "ttl": "30d",
    "graphId": 5,
    "online": 1,
    "source": 13,
    "type": "medium_user_id2apdid_login",
    "target": 26,
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "medium_user_id2apdid_login",
    "gmtCreate": "2018-04-04 11:53:24",
    "id": 125,
    "status": 60,
    "uniqueId": 125
  }, {
    "rate": -3,
    "elementType": "E",
    "directed": "Y",
    "update": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"src\",\"propName\":\"src_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dst\",\"propName\":\"dst_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"srcType\",\"propName\":\"src_type\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dstType\",\"propName\":\"dst_type\",\"propOnLine\":1}]",
    "ttl": "30d",
    "graphId": 5,
    "online": 1,
    "source": 13,
    "type": "medium_user_id2apdid_maintrade",
    "target": 26,
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "medium_user_id2apdid_maintrade",
    "gmtCreate": "2018-04-04 11:55:56",
    "id": 126,
    "status": 60,
    "uniqueId": 126
  }, {
    "rate": -2,
    "elementType": "E",
    "directed": "Y",
    "update": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"src\",\"propName\":\"src_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dst\",\"propName\":\"dst_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"srcType\",\"propName\":\"src_type\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dstType\",\"propName\":\"dst_type\",\"propOnLine\":1}]",
    "ttl": "30d",
    "graphId": 5,
    "online": 1,
    "source": 13,
    "type": "medium_user_id2apdid_highrisk",
    "target": 26,
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "medium_user_id2apdid_highrisk",
    "gmtCreate": "2018-04-04 11:56:39",
    "id": 127,
    "status": 60,
    "uniqueId": 127
  }, {
    "rate": -1,
    "elementType": "E",
    "directed": "Y",
    "update": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"src\",\"propName\":\"src_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dst\",\"propName\":\"dst_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"srcType\",\"propName\":\"src_type\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dstType\",\"propName\":\"dst_type\",\"propOnLine\":1}]",
    "ttl": "30d",
    "graphId": 5,
    "online": 1,
    "source": 13,
    "type": "medium_user_id2apdid_trade",
    "target": 26,
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "medium_user_id2apdid_trade",
    "gmtCreate": "2018-04-04 11:57:21",
    "id": 128,
    "status": 60,
    "uniqueId": 128
  }, {
    "rate": 0,
    "elementType": "E",
    "directed": "Y",
    "update": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"src\",\"propName\":\"src_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dst\",\"propName\":\"dst_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"srcType\",\"propName\":\"src_type\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dstType\",\"propName\":\"dst_type\",\"propOnLine\":1}]",
    "ttl": "30d",
    "graphId": 5,
    "online": 1,
    "source": 13,
    "type": "medium_user_id2apdid_tenant",
    "target": 26,
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "medium_user_id2apdid_tenant",
    "gmtCreate": "2018-04-04 11:58:34",
    "id": 129,
    "status": 60,
    "uniqueId": 129
  }, {
    "rate": 1,
    "elementType": "E",
    "directed": "Y",
    "update": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"src\",\"propName\":\"src_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dst\",\"propName\":\"dst_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"srcType\",\"propName\":\"src_type\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dstType\",\"propName\":\"dst_type\",\"propOnLine\":1}]",
    "ttl": "30d",
    "graphId": 5,
    "online": 1,
    "source": 13,
    "type": "medium_user_id2apdid_otherpay",
    "target": 26,
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "medium_user_id2apdid_otherpay",
    "gmtCreate": "2018-04-04 11:59:12",
    "id": 130,
    "status": 60,
    "uniqueId": 130
  }, {
    "rate": 2,
    "elementType": "E",
    "directed": "Y",
    "update": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"src\",\"propName\":\"src_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dst\",\"propName\":\"dst_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"srcType\",\"propName\":\"src_type\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dstType\",\"propName\":\"dst_type\",\"propOnLine\":1}]",
    "ttl": "30d",
    "graphId": 5,
    "online": 1,
    "source": 13,
    "type": "medium_user_id2apdid_auth",
    "target": 26,
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "medium_user_id2apdid_auth",
    "gmtCreate": "2018-04-04 11:59:51",
    "id": 131,
    "status": 60,
    "uniqueId": 131
  }, {
    "rate": 3,
    "elementType": "E",
    "directed": "Y",
    "update": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"src\",\"propName\":\"src_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dst\",\"propName\":\"dst_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"srcType\",\"propName\":\"src_type\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dstType\",\"propName\":\"dst_type\",\"propOnLine\":1}]",
    "ttl": "30d",
    "graphId": 5,
    "online": 1,
    "source": 13,
    "type": "medium_user_id2apdid_register",
    "target": 26,
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "medium_user_id2apdid_register",
    "gmtCreate": "2018-04-04 12:00:45",
    "id": 132,
    "status": 60,
    "uniqueId": 132
  }, {
    "rate": -4,
    "elementType": "E",
    "directed": "Y",
    "update": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"src\",\"propName\":\"src_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dst\",\"propName\":\"dst_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"srcType\",\"propName\":\"src_type\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dstType\",\"propName\":\"dst_type\",\"propOnLine\":1}]",
    "ttl": "30d",
    "graphId": 5,
    "online": 1,
    "source": 13,
    "type": "medium_user_id2ip3_wifi_login",
    "target": 27,
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "medium_user_id2ip3_wifi_login",
    "gmtCreate": "2018-04-04 12:01:26",
    "id": 133,
    "status": 60,
    "uniqueId": 133
  }, {
    "rate": -3,
    "elementType": "E",
    "directed": "Y",
    "update": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"src\",\"propName\":\"src_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dst\",\"propName\":\"dst_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"srcType\",\"propName\":\"src_type\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dstType\",\"propName\":\"dst_type\",\"propOnLine\":1}]",
    "ttl": "30d",
    "graphId": 5,
    "online": 1,
    "source": 13,
    "type": "medium_user_id2ip3_wifi_maintrade",
    "target": 27,
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "medium_user_id2ip3_wifi_maintrade",
    "gmtCreate": "2018-04-04 12:02:05",
    "id": 134,
    "status": 60,
    "uniqueId": 134
  }, {
    "rate": -2,
    "elementType": "E",
    "directed": "Y",
    "update": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"src\",\"propName\":\"src_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dst\",\"propName\":\"dst_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"srcType\",\"propName\":\"src_type\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dstType\",\"propName\":\"dst_type\",\"propOnLine\":1}]",
    "ttl": "30d",
    "graphId": 5,
    "online": 1,
    "source": 13,
    "type": "medium_user_id2ip3_wifi_highrisk",
    "target": 27,
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "medium_user_id2ip3_wifi_highrisk",
    "gmtCreate": "2018-04-04 13:17:49",
    "id": 135,
    "status": 60,
    "uniqueId": 135
  }, {
    "rate": -1,
    "elementType": "E",
    "directed": "Y",
    "update": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"src\",\"propName\":\"src_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dst\",\"propName\":\"dst_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"srcType\",\"propName\":\"src_type\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dstType\",\"propName\":\"dst_type\",\"propOnLine\":1}]",
    "ttl": "30d",
    "graphId": 5,
    "online": 1,
    "source": 13,
    "type": "medium_user_id2ip3_wifi_trade",
    "target": 27,
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "medium_user_id2ip3_wifi_trade",
    "gmtCreate": "2018-04-04 13:18:35",
    "id": 136,
    "status": 60,
    "uniqueId": 136
  }, {
    "rate": 0,
    "elementType": "E",
    "directed": "Y",
    "update": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"src\",\"propName\":\"src_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dst\",\"propName\":\"dst_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"srcType\",\"propName\":\"src_type\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dstType\",\"propName\":\"dst_type\",\"propOnLine\":1}]",
    "ttl": "30d",
    "graphId": 5,
    "online": 1,
    "source": 13,
    "type": "medium_user_id2ip3_wifi_tenant",
    "target": 27,
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "medium_user_id2ip3_wifi_tenant",
    "gmtCreate": "2018-04-04 13:19:24",
    "id": 137,
    "status": 60,
    "uniqueId": 137
  }, {
    "rate": 1,
    "elementType": "E",
    "directed": "Y",
    "update": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"src\",\"propName\":\"src_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dst\",\"propName\":\"dst_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"srcType\",\"propName\":\"src_type\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dstType\",\"propName\":\"dst_type\",\"propOnLine\":1}]",
    "ttl": "30d",
    "graphId": 5,
    "online": 1,
    "source": 13,
    "type": "medium_user_id2ip3_wifi_otherpay",
    "target": 27,
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "medium_user_id2ip3_wifi_otherpay",
    "gmtCreate": "2018-04-04 13:35:26",
    "id": 138,
    "status": 60,
    "uniqueId": 138
  }, {
    "rate": 2,
    "elementType": "E",
    "directed": "Y",
    "update": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"src\",\"propName\":\"src_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dst\",\"propName\":\"dst_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"srcType\",\"propName\":\"src_type\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dstType\",\"propName\":\"dst_type\",\"propOnLine\":1}]",
    "ttl": "30d",
    "graphId": 5,
    "online": 1,
    "source": 13,
    "type": "medium_user_id2ip3_wifi_auth",
    "target": 27,
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "medium_user_id2ip3_wifi_auth",
    "gmtCreate": "2018-04-04 13:36:07",
    "id": 139,
    "status": 60,
    "uniqueId": 139
  }, {
    "rate": 3,
    "elementType": "E",
    "directed": "Y",
    "update": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"src\",\"propName\":\"src_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dst\",\"propName\":\"dst_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"srcType\",\"propName\":\"src_type\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dstType\",\"propName\":\"dst_type\",\"propOnLine\":1}]",
    "ttl": "30d",
    "graphId": 5,
    "online": 1,
    "source": 13,
    "type": "medium_user_id2ip3_wifi_register",
    "target": 27,
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "medium_user_id2ip3_wifi_register",
    "gmtCreate": "2018-04-04 13:36:59",
    "id": 140,
    "status": 60,
    "uniqueId": 140
  }, {
    "rate": -4,
    "elementType": "E",
    "directed": "Y",
    "update": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"src\",\"propName\":\"src_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dst\",\"propName\":\"dst_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"srcType\",\"propName\":\"src_type\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dstType\",\"propName\":\"dst_type\",\"propOnLine\":1}]",
    "ttl": "30d",
    "graphId": 5,
    "online": 1,
    "source": 13,
    "type": "medium_user_id2ip_login",
    "target": 28,
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "medium_user_id2ip_login",
    "gmtCreate": "2018-04-04 13:37:59",
    "id": 141,
    "status": 60,
    "uniqueId": 141
  }, {
    "rate": -3,
    "elementType": "E",
    "directed": "Y",
    "update": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"src\",\"propName\":\"src_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dst\",\"propName\":\"dst_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"srcType\",\"propName\":\"src_type\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dstType\",\"propName\":\"dst_type\",\"propOnLine\":1}]",
    "ttl": "30d",
    "graphId": 5,
    "online": 1,
    "source": 13,
    "type": "medium_user_id2ip_maintrade",
    "target": 28,
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "medium_user_id2ip_maintrade",
    "gmtCreate": "2018-04-04 13:38:42",
    "id": 142,
    "status": 60,
    "uniqueId": 142
  }, {
    "rate": -2,
    "elementType": "E",
    "directed": "Y",
    "update": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"src\",\"propName\":\"src_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dst\",\"propName\":\"dst_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"srcType\",\"propName\":\"src_type\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dstType\",\"propName\":\"dst_type\",\"propOnLine\":1}]",
    "ttl": "30d",
    "graphId": 5,
    "online": 1,
    "source": 13,
    "type": "medium_user_id2ip_highrisk",
    "target": 28,
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "medium_user_id2ip_highrisk",
    "gmtCreate": "2018-04-04 13:39:26",
    "id": 143,
    "status": 60,
    "uniqueId": 143
  }, {
    "rate": -1,
    "elementType": "E",
    "directed": "Y",
    "update": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"src\",\"propName\":\"src_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dst\",\"propName\":\"dst_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"srcType\",\"propName\":\"src_type\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dstType\",\"propName\":\"dst_type\",\"propOnLine\":1}]",
    "ttl": "30d",
    "graphId": 5,
    "online": 1,
    "source": 13,
    "type": "medium_user_id2ip_trade",
    "target": 28,
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "medium_user_id2ip_trade",
    "gmtCreate": "2018-04-04 13:40:12",
    "id": 144,
    "status": 60,
    "uniqueId": 144
  }, {
    "rate": 0,
    "elementType": "E",
    "directed": "Y",
    "update": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"src\",\"propName\":\"src_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dst\",\"propName\":\"dst_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"srcType\",\"propName\":\"src_type\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dstType\",\"propName\":\"dst_type\",\"propOnLine\":1}]",
    "ttl": "30d",
    "graphId": 5,
    "online": 1,
    "source": 13,
    "type": "medium_user_id2ip_tenant",
    "target": 28,
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "medium_user_id2ip_tenant",
    "gmtCreate": "2018-04-04 13:40:53",
    "id": 145,
    "status": 60,
    "uniqueId": 145
  }, {
    "rate": 1,
    "elementType": "E",
    "directed": "Y",
    "update": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"src\",\"propName\":\"src_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dst\",\"propName\":\"dst_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"srcType\",\"propName\":\"src_type\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dstType\",\"propName\":\"dst_type\",\"propOnLine\":1}]",
    "ttl": "30d",
    "graphId": 5,
    "online": 1,
    "source": 13,
    "type": "medium_user_id2ip_otherpay",
    "target": 28,
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "medium_user_id2ip_otherpay",
    "gmtCreate": "2018-04-04 13:41:34",
    "id": 146,
    "status": 60,
    "uniqueId": 146
  }, {
    "rate": 2,
    "elementType": "E",
    "directed": "Y",
    "update": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"src\",\"propName\":\"src_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dst\",\"propName\":\"dst_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"srcType\",\"propName\":\"src_type\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dstType\",\"propName\":\"dst_type\",\"propOnLine\":1}]",
    "ttl": "30d",
    "graphId": 5,
    "online": 1,
    "source": 13,
    "type": "medium_user_id2ip_auth",
    "target": 28,
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "medium_user_id2ip_auth",
    "gmtCreate": "2018-04-04 13:42:18",
    "id": 147,
    "status": 60,
    "uniqueId": 147
  }, {
    "rate": 3,
    "elementType": "E",
    "directed": "Y",
    "update": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"src\",\"propName\":\"src_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dst\",\"propName\":\"dst_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"srcType\",\"propName\":\"src_type\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dstType\",\"propName\":\"dst_type\",\"propOnLine\":1}]",
    "ttl": "30d",
    "graphId": 5,
    "online": 1,
    "source": 13,
    "type": "medium_user_id2ip_register",
    "target": 28,
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "medium_user_id2ip_register",
    "gmtCreate": "2018-04-04 13:42:59",
    "id": 148,
    "status": 60,
    "uniqueId": 148
  }, {
    "rate": 0,
    "elementType": "E",
    "directed": "Y",
    "update": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"src\",\"propName\":\"src_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dst\",\"propName\":\"dst_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"srcType\",\"propName\":\"src_type\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dstType\",\"propName\":\"dst_type\",\"propOnLine\":1}]",
    "ttl": "30d",
    "graphId": 5,
    "online": 1,
    "source": 12,
    "type": "medium_merchant_id2web_url_offline",
    "target": 21,
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "medium_merchant_id2web_url_offline",
    "gmtCreate": "2018-04-13 11:58:45",
    "id": 149,
    "status": 60,
    "uniqueId": 149
  }, {
    "rate": 0,
    "elementType": "E",
    "directed": "Y",
    "update": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"src\",\"propName\":\"src_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dst\",\"propName\":\"dst_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"srcType\",\"propName\":\"src_type\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"dstType\",\"propName\":\"dst_type\",\"propOnLine\":1}]",
    "ttl": "30d",
    "graphId": 5,
    "online": 1,
    "source": 12,
    "type": "medium_merchant_id2wx_qq_offline",
    "target": 20,
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "medium_merchant_id2wx_qq_offline",
    "gmtCreate": "2018-04-13 11:59:44",
    "id": 152,
    "status": 60,
    "uniqueId": 152
  }],
  "nodeList": [{
    "relateNodeCnt": 64,
    "elementType": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"id\",\"propName\":\"node_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"分值 0 白/1 黑\",\"propName\":\"black_score\",\"propOnLine\":1}]",
    "graphId": 5,
    "online": 1,
    "type": "medium_user_id",
    "owner": "",
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "用户ID",
    "gmtCreate": "2018-04-03 14:00:39",
    "id": 13,
    "status": 60,
    "uniqueId": 13
  }, {
    "relateNodeCnt": 8,
    "elementType": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"id\",\"propName\":\"node_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"分值 0 白/1 黑\",\"propName\":\"black_score\",\"propOnLine\":1}]",
    "graphId": 5,
    "online": 1,
    "type": "medium_umid",
    "owner": " ",
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "umid",
    "gmtCreate": "2018-04-03 14:26:10",
    "id": 22,
    "status": 60,
    "uniqueId": 22
  }, {
    "relateNodeCnt": 8,
    "elementType": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"id\",\"propName\":\"node_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"分值 0 白/1 黑\",\"propName\":\"black_score\",\"propOnLine\":1}]",
    "graphId": 5,
    "online": 1,
    "type": "medium_tid",
    "owner": " ",
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "设备标识TID",
    "gmtCreate": "2018-04-03 14:27:46",
    "id": 23,
    "status": 60,
    "uniqueId": 23
  }, {
    "relateNodeCnt": 8,
    "elementType": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"id\",\"propName\":\"node_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"分值 0 白/1 黑\",\"propName\":\"black_score\",\"propOnLine\":1}]",
    "graphId": 5,
    "online": 1,
    "type": "medium_sim",
    "owner": " ",
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "sim卡号",
    "gmtCreate": "2018-04-03 14:29:04",
    "id": 25,
    "status": 60,
    "uniqueId": 25
  }, {
    "relateNodeCnt": 8,
    "elementType": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"id\",\"propName\":\"node_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"分值 0 白/1 黑\",\"propName\":\"black_score\",\"propOnLine\":1}]",
    "graphId": 5,
    "online": 1,
    "type": "medium_apdid",
    "owner": " ",
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "设备指纹APDID",
    "gmtCreate": "2018-04-03 14:29:49",
    "id": 26,
    "status": 60,
    "uniqueId": 26
  }, {
    "relateNodeCnt": 8,
    "elementType": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"id\",\"propName\":\"node_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"分值 0 白/1 黑\",\"propName\":\"black_score\",\"propOnLine\":1}]",
    "graphId": 5,
    "online": 1,
    "type": "medium_ip3_wifi",
    "owner": " ",
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "由client_ip,wifi名称以及WiFi网关MAC（wmac）拼接",
    "gmtCreate": "2018-04-03 14:30:37",
    "id": 27,
    "status": 60,
    "uniqueId": 27
  }, {
    "relateNodeCnt": 8,
    "elementType": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"id\",\"propName\":\"node_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"分值 0 白/1 黑\",\"propName\":\"black_score\",\"propOnLine\":1}]",
    "graphId": 5,
    "online": 1,
    "type": "medium_ip",
    "owner": "",
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "ip",
    "gmtCreate": "2018-04-03 14:32:04",
    "id": 28,
    "status": 60,
    "uniqueId": 28
  }, {
    "relateNodeCnt": 4,
    "elementType": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"id\",\"propName\":\"node_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"分值 0 白/1 黑\",\"propName\":\"black_score\",\"propOnLine\":1}]",
    "graphId": 5,
    "online": 1,
    "type": "medium_merchant_id",
    "owner": " ",
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "商户点",
    "gmtCreate": "2018-04-03 13:55:59",
    "id": 12,
    "status": 60,
    "uniqueId": 12
  }, {
    "relateNodeCnt": 2,
    "elementType": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"id\",\"propName\":\"node_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"分值 0 白/1 黑\",\"propName\":\"black_score\",\"propOnLine\":1}]",
    "graphId": 5,
    "online": 1,
    "type": "medium_wx_qq",
    "owner": " ",
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "wx qq号",
    "gmtCreate": "2018-04-03 14:24:31",
    "id": 20,
    "status": 60,
    "uniqueId": 20
  }, {
    "relateNodeCnt": 2,
    "elementType": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"id\",\"propName\":\"node_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"分值 0 白/1 黑\",\"propName\":\"black_score\",\"propOnLine\":1}]",
    "graphId": 5,
    "online": 1,
    "type": "medium_web_url",
    "owner": " ",
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "url",
    "gmtCreate": "2018-04-03 14:25:34",
    "id": 21,
    "status": 60,
    "uniqueId": 21
  }, {
    "relateNodeCnt": 1,
    "elementType": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"id\",\"propName\":\"node_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"分值 0 白/1 黑\",\"propName\":\"black_score\",\"propOnLine\":1}]",
    "graphId": 5,
    "online": 1,
    "type": "medium_cert_no",
    "owner": " ",
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "身份证",
    "gmtCreate": "2018-04-03 14:02:00",
    "id": 14,
    "status": 60,
    "uniqueId": 14
  }, {
    "relateNodeCnt": 1,
    "elementType": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"id\",\"propName\":\"node_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"分值 0 白/1 黑\",\"propName\":\"black_score\",\"propOnLine\":1}]",
    "graphId": 5,
    "online": 1,
    "type": "medium_license_number",
    "owner": " ",
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "营业执照",
    "gmtCreate": "2018-04-03 14:03:25",
    "id": 15,
    "status": 60,
    "uniqueId": 15
  }, {
    "relateNodeCnt": 1,
    "elementType": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"id\",\"propName\":\"node_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"分值 0 白/1 黑\",\"propName\":\"black_score\",\"propOnLine\":1}]",
    "graphId": 5,
    "online": 1,
    "type": "medium_bank_card_no",
    "owner": " ",
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "绑定、提现、签约、认证卡信息",
    "gmtCreate": "2018-04-03 14:04:26",
    "id": 16,
    "status": 60,
    "uniqueId": 16
  }, {
    "relateNodeCnt": 1,
    "elementType": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"id\",\"propName\":\"node_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"分值 0 白/1 黑\",\"propName\":\"black_score\",\"propOnLine\":1}]",
    "graphId": 5,
    "online": 1,
    "type": "medium_phone_no",
    "owner": " ",
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "电话号码",
    "gmtCreate": "2018-04-03 14:22:30",
    "id": 18,
    "status": 60,
    "uniqueId": 18
  }, {
    "relateNodeCnt": 1,
    "elementType": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"id\",\"propName\":\"node_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"分值 0 白/1 黑\",\"propName\":\"black_score\",\"propOnLine\":1}]",
    "graphId": 5,
    "online": 1,
    "type": "medium_isv_pid",
    "owner": " ",
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "合作伙伴pid",
    "gmtCreate": "2018-04-03 14:23:27",
    "id": 19,
    "status": 60,
    "uniqueId": 19
  }, {
    "relateNodeCnt": 1,
    "elementType": "N",
    "prop": "[{\"propDataType\":\"string\",\"propDesc\":\"id\",\"propName\":\"node_id\",\"propOnLine\":1},{\"propDataType\":\"string\",\"propDesc\":\"分值 0 白/1 黑\",\"propName\":\"black_score\",\"propOnLine\":1}]",
    "graphId": 5,
    "online": 1,
    "type": "medium_receiver_card_no",
    "owner": " ",
    "gmtModified": "2018-04-16 16:18:25",
    "descption": "转账到同名卡",
    "gmtCreate": "2018-04-04 10:31:03",
    "id": 29,
    "status": 60,
    "uniqueId": 29
  }, {
    "relateNodeCnt": 0,
    "elementType": "N",
    "prop": "[{\"propName\":\"node_id\",\"propDesc\":\"node\",\"propDataType\":\"string\",\"propOnLine\":0},{\"propName\":\"black_score\",\"propDesc\":\"score\",\"propDataType\":\"string\",\"propOnLine\":0}]",
    "graphId": 5,
    "online": 0,
    "type": "medium_imei",
    "owner": " ",
    "gmtModified": "2018-04-04 15:16:45",
    "descption": "medium_imei",
    "gmtCreate": "2018-04-04 15:09:29",
    "id": 31,
    "status": 999,
    "uniqueId": 31
  }, {
    "relateNodeCnt": 0,
    "elementType": "N",
    "prop": "[{\"propDataType\":\"string\",\"propOnLine\":1,\"propName\":\"node_id\",\"propDesc\":\"imei\"},{\"propDataType\":\"string\",\"propOnLine\":1,\"propName\":\"black_score\",\"propDesc\":\"分值0 白/1 黑\"}]",
    "graphId": 5,
    "online": 1,
    "type": "meidum_imei",
    "owner": " ",
    "gmtModified": "2018-04-04 15:19:20",
    "descption": "imei",
    "gmtCreate": "2018-04-04 15:16:23",
    "id": 32,
    "status": 70,
    "uniqueId": 24
  }]
};

exports = module.exports = data;